/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2026-01-07 08:10:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.board;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1764828076780L));
    _jspx_dependants.put("jar:file:/C:/Users/M/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>관리자 - 게시판 관리</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body { margin: 0; font-family: 'Malgun Gothic', sans-serif; display: flex; background-color: #f4f7f6; }\r\n");
      out.write("    \r\n");
      out.write("    /* 사이드바 스타일 */\r\n");
      out.write("    .sidebar { width: 240px; background: #2c3e50; color: white; height: 100vh; position: fixed; }\r\n");
      out.write("    .sidebar-header { padding: 20px; text-align: center; background: #1a252f; font-size: 20px; font-weight: bold; }\r\n");
      out.write("    .sidebar-menu { padding: 0; list-style: none; }\r\n");
      out.write("    .sidebar-menu li a { display: block; padding: 15px 25px; color: #bdc3c7; text-decoration: none; border-bottom: 1px solid #34495e; }\r\n");
      out.write("    .sidebar-menu li a:hover { background: #34495e; color: white; }\r\n");
      out.write("    .sidebar-menu li a.active { background: #3498db; color: white; }\r\n");
      out.write("\r\n");
      out.write("    /* 메인 영역 */\r\n");
      out.write("    .main-content { margin-left: 240px; width: calc(100% - 240px); }\r\n");
      out.write("    .container { padding: 30px; }\r\n");
      out.write("    .page-title { margin-bottom: 20px; color: #333; }\r\n");
      out.write("    \r\n");
      out.write("    /* 검색 영역 스타일 (요청하신 search-wrapper 규격) */\r\n");
      out.write("    .search-wrapper { margin-bottom: 20px; display: flex; justify-content: flex-end; gap: 8px; }\r\n");
      out.write("    .search-wrapper select, .search-wrapper input { padding: 8px; border: 1px solid #ddd; border-radius: 4px; outline: none; }\r\n");
      out.write("    .search-wrapper button { padding: 8px 18px; background: #2c3e50; color: white; border: none; border-radius: 4px; cursor: pointer; }\r\n");
      out.write("    .search-wrapper button:hover { background: #1a252f; }\r\n");
      out.write("\r\n");
      out.write("    /* 테이블 스타일 */\r\n");
      out.write("    .admin-table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }\r\n");
      out.write("    .admin-table th { background: #f8f9fa; padding: 15px; border-bottom: 2px solid #dee2e6; color: #495057; font-size: 14px; }\r\n");
      out.write("    .admin-table td { padding: 15px; border-bottom: 1px solid #eee; text-align: center; font-size: 14px; color: #666; }\r\n");
      out.write("    \r\n");
      out.write("    /* 삭제된 게시글 상태 스타일 */\r\n");
      out.write("    .deleted-row { background-color: #fafafa; }\r\n");
      out.write("    .deleted-row td { color: #ccc !important; }\r\n");
      out.write("    .deleted-title { text-decoration: line-through; color: #bbb !important; }\r\n");
      out.write("    .title-cell { text-align: left !important; }\r\n");
      out.write("    .title-cell a { color: #333; text-decoration: none; font-weight: bold; }\r\n");
      out.write("    \r\n");
      out.write("    /* 버튼 스타일 */\r\n");
      out.write("    .btn-action { border: none; padding: 8px 12px; border-radius: 4px; cursor: pointer; font-size: 12px; color: white; min-width: 60px; }\r\n");
      out.write("    .btn-delete { background: #e74c3c; } \r\n");
      out.write("    .btn-restore { background: #2ecc71; } \r\n");
      out.write("\r\n");
      out.write("    /* 페이징 */\r\n");
      out.write("    .pagination { display: flex; justify-content: center; list-style: none; padding: 0; margin-top: 30px; gap: 5px; }\r\n");
      out.write("    .pagination li a { display: block; padding: 8px 14px; border: 1px solid #ddd; text-decoration: none; color: #333; border-radius: 4px; background: white; }\r\n");
      out.write("    .pagination li.active a { background: #3498db; color: white; border-color: #3498db; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-header\">게시판 관리</div>\r\n");
      out.write("        <ul class=\"sidebar-menu\">\r\n");
      out.write("            <li><a href=\"/admin/main\">대시보드 메인</a></li>\r\n");
      out.write("            <li><a href=\"/admin/board/list\" class=\"active\">게시판 관리</a></li>\r\n");
      out.write("            <li><a href=\"/admin/member/list\">회원 관리</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/adminHeader.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h1 class=\"page-title\">게시판 관리</h1>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"search-wrapper\">\r\n");
      out.write("                <select id=\"searchType\">\r\n");
      out.write("                    <option value=\"t\">제목</option>\r\n");
      out.write("                    <option value=\"c\">내용</option>\r\n");
      out.write("                    <option value=\"w\">작성자</option>\r\n");
      out.write("                    <option value=\"tc\">제목+내용</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <input type=\"text\" id=\"searchKeyword\" placeholder=\"검색어를 입력하세요\" onkeyup=\"if(window.event.keyCode==13){loadAdminList(1)}\">\r\n");
      out.write("                <button type=\"button\" onclick=\"loadAdminList(1)\">검색</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <table class=\"admin-table\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th width=\"130\">번호</th>\r\n");
      out.write("                        <th>제목</th>\r\n");
      out.write("                        <th width=\"200\">작성자</th>\r\n");
      out.write("                        <th width=\"200\">작성일</th>\r\n");
      out.write("                        <th width=\"100\">조회수</th>\r\n");
      out.write("                        <th width=\"150\">상태변경</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody id=\"adminBoardList\">\r\n");
      out.write("                    <tr><td colspan=\"6\" style=\"padding:50px;\">데이터를 불러오는 중...</td></tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"pagination\" id=\"adminPaging\"></ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    let currentPage = 1;\r\n");
      out.write("\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("        loadAdminList(1);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function loadAdminList(page) {\r\n");
      out.write("        currentPage = page;\r\n");
      out.write("        const type = document.getElementById(\"searchType\").value;\r\n");
      out.write("        const keyword = document.getElementById(\"searchKeyword\").value;\r\n");
      out.write("        const url = `/admin/board/api/list?page=${page}&size=10&types=${type}&keyword=${encodeURIComponent(keyword)}`;\r\n");
      out.write("        \r\n");
      out.write("        fetch(url)\r\n");
      out.write("            .then(res => res.json())\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                printTable(data.boardDTOList);\r\n");
      out.write("                printPaging(data);\r\n");
      out.write("            })\r\n");
      out.write("            .catch(err => {\r\n");
      out.write("                console.error(err);\r\n");
      out.write("                document.getElementById(\"adminBoardList\").innerHTML = '<tr><td colspan=\"6\" style=\"padding:50px; color:red;\">데이터 로드 실패</td></tr>';\r\n");
      out.write("            });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function printTable(list) {\r\n");
      out.write("        const tbody = document.getElementById(\"adminBoardList\");\r\n");
      out.write("        let str = \"\";\r\n");
      out.write("        \r\n");
      out.write("        if(list && list.length > 0) {\r\n");
      out.write("            list.forEach(board => {\r\n");
      out.write("                const isDeleted = (board.delflag == 1); \r\n");
      out.write("                const rowClass = isDeleted ? \"deleted-row\" : \"\";\r\n");
      out.write("                const titleClass = isDeleted ? \"deleted-title\" : \"\";\r\n");
      out.write("                \r\n");
      out.write("                const actionBtn = isDeleted \r\n");
      out.write("                    ? `<button type=\"button\" class=\"btn-action btn-restore\" onclick=\"handleStatus(${board.seq}, 'restore')\">복원</button>`\r\n");
      out.write("                    : `<button type=\"button\" class=\"btn-action btn-delete\" onclick=\"handleStatus(${board.seq}, 'delete')\">삭제</button>`;\r\n");
      out.write("\r\n");
      out.write("                str += `<tr class=\"${rowClass}\">\r\n");
      out.write("                    <td>${board.seq}</td>\r\n");
      out.write("                    <td class=\"title-cell\">\r\n");
      out.write("                        <a href=\"/board/detail?seq=${board.seq}\" target=\"_blank\" class=\"${titleClass}\">${board.title}</a>\r\n");
      out.write("                        ${isDeleted ? ' <small style=\"color:red; font-weight:normal;\">(삭제됨)</small>' : ''}\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>${board.writer}</td>\r\n");
      out.write("                    <td>${board.regdateShort}</td>\r\n");
      out.write("                    <td>${board.hit}</td>\r\n");
      out.write("                    <td>${actionBtn}</td>\r\n");
      out.write("                </tr>`;\r\n");
      out.write("            });\r\n");
      out.write("        } else {\r\n");
      out.write("            str = \"<tr><td colspan='6' style='padding:50px; color:#ccc;'>게시글이 존재하지 않습니다.</td></tr>\";\r\n");
      out.write("        }\r\n");
      out.write("        tbody.innerHTML = str;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function handleStatus(seq, mode) {\r\n");
      out.write("        const actionText = (mode === 'restore') ? \"복원\" : \"삭제\";\r\n");
      out.write("        if(!confirm(seq + \"번 게시글을 \" + actionText + \"하시겠습니까?\")) return;\r\n");
      out.write("\r\n");
      out.write("        const url = (mode === 'restore') ? \"/admin/boardRestore\" : \"/admin/boardDelete\";\r\n");
      out.write("\r\n");
      out.write("        fetch(url, {\r\n");
      out.write("            method: 'POST',\r\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\r\n");
      out.write("            body: \"seq=\" + seq\r\n");
      out.write("        })\r\n");
      out.write("        .then(res => res.text())\r\n");
      out.write("        .then(result => {\r\n");
      out.write("            if(result === \"success\") {\r\n");
      out.write("                alert(actionText + \"되었습니다.\");\r\n");
      out.write("                loadAdminList(currentPage);\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(actionText + \" 실패\");\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        .catch(err => alert(\"오류 발생\"));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function printPaging(data) {\r\n");
      out.write("        const pagingUl = document.getElementById(\"adminPaging\");\r\n");
      out.write("        let str = \"\";\r\n");
      out.write("        if(data.prev) str += `<li><a href=\"javascript:loadAdminList(${data.start - 1})\">이전</a></li>`;\r\n");
      out.write("        data.pageNums.forEach(num => {\r\n");
      out.write("            const activeClass = (data.page === num) ? \"active\" : \"\";\r\n");
      out.write("            str += `<li class=\"${activeClass}\"><a href=\"javascript:loadAdminList(${num})\">${num}</a></li>`;\r\n");
      out.write("        });\r\n");
      out.write("        if(data.next) str += `<li><a href=\"javascript:loadAdminList(${data.end + 1})\">다음</a></li>`;\r\n");
      out.write("        pagingUl.innerHTML = str;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
