/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2026-01-07 08:09:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1764828076780L));
    _jspx_dependants.put("jar:file:/C:/Users/M/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>관리자 페이지 - 메인</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body { margin: 0; font-family: 'Malgun Gothic', sans-serif; display: flex; background-color: #f4f7f6; }\r\n");
      out.write("    \r\n");
      out.write("    /* 사이드바 스타일 */\r\n");
      out.write("    .sidebar { width: 240px; background: #2c3e50; color: white; height: 100vh; position: fixed; }\r\n");
      out.write("    .sidebar-header { padding: 20px; text-align: center; background: #1a252f; font-size: 20px; font-weight: bold; }\r\n");
      out.write("    .sidebar-menu { padding: 0; list-style: none; }\r\n");
      out.write("    .sidebar-menu li a { display: block; padding: 15px 25px; color: #bdc3c7; text-decoration: none; border-bottom: 1px solid #34495e; transition: 0.3s; }\r\n");
      out.write("    .sidebar-menu li a:hover { background: #34495e; color: white; }\r\n");
      out.write("    .sidebar-menu li a.active { background: #3498db; color: white; }\r\n");
      out.write("\r\n");
      out.write("    /* 메인 영역 스타일 */\r\n");
      out.write("    .main-content { margin-left: 240px; width: calc(100% - 240px); display: flex; flex-direction: column; }\r\n");
      out.write("    \r\n");
      out.write("    /* 대시보드 내용 */\r\n");
      out.write("    .container { padding: 30px; }\r\n");
      out.write("    .dashboard-cards { display: flex; gap: 20px; margin-top: 20px; }\r\n");
      out.write("    .card { background: white; padding: 20px; border-radius: 8px; flex: 1; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border-left: 5px solid #3498db; }\r\n");
      out.write("    .card h3 { margin: 0; font-size: 14px; color: #7f8c8d; }\r\n");
      out.write("    .card .value { font-size: 28px; font-weight: bold; margin-top: 10px; color: #2c3e50; }\r\n");
      out.write("    \r\n");
      out.write("    /* 최근 가입자 섹션 컨테이너 */\r\n");
      out.write("	.recent-members-section {\r\n");
      out.write("	    margin-top: 40px;\r\n");
      out.write("	    background: white;\r\n");
      out.write("	    padding: 25px;\r\n");
      out.write("	    border-radius: 12px;\r\n");
      out.write("	    box-shadow: 0 4px 20px rgba(0,0,0,0.08);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.recent-members-section h3 {\r\n");
      out.write("	    margin-top: 0;\r\n");
      out.write("	    margin-bottom: 20px;\r\n");
      out.write("	    font-size: 18px;\r\n");
      out.write("	    color: #2c3e50;\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    align-items: center;\r\n");
      out.write("	    gap: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.recent-members-section h3::before {\r\n");
      out.write("	    content: \"\";\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	    width: 8px;\r\n");
      out.write("	    height: 8px;\r\n");
      out.write("	    background-color: #3498db;\r\n");
      out.write("	    border-radius: 50%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.admin-mini-table { width: 100%; border-collapse: collapse; }\r\n");
      out.write("	.admin-mini-table th {\r\n");
      out.write("	    background-color: #f8f9fa;\r\n");
      out.write("	    color: #7f8c8d;\r\n");
      out.write("	    font-size: 13px;\r\n");
      out.write("	    font-weight: 600;\r\n");
      out.write("	    padding: 12px 15px;\r\n");
      out.write("	    text-align: left;\r\n");
      out.write("	    border-top: 1px solid #edf2f7;\r\n");
      out.write("	    border-bottom: 2px solid #edf2f7;\r\n");
      out.write("	}\r\n");
      out.write("	.admin-mini-table td { padding: 14px 15px; border-bottom: 1px solid #f1f5f9; font-size: 14px; color: #4a5568; }\r\n");
      out.write("	.admin-mini-table tr:last-child td { border-bottom: none; }\r\n");
      out.write("	.admin-mini-table tr:hover { background-color: #fcfdfe; }\r\n");
      out.write("	.user-id { font-weight: bold; color: #2d3748; }\r\n");
      out.write("	.reg-date { color: #a0aec0; font-size: 12px; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-header\">관리자 페이지</div>\r\n");
      out.write("        <ul class=\"sidebar-menu\">\r\n");
      out.write("            <li><a href=\"/admin/main\" class=\"active\">대시보드 메인</a></li>\r\n");
      out.write("            <li><a href=\"/admin/board/list\">게시판 관리</a></li>\r\n");
      out.write("            <li><a href=\"/admin/member/list\">회원 관리</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/adminHeader.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h1>대시보드</h1>\r\n");
      out.write("            <p>사이트의 현재 현황을 요약해서 보여줍니다.</p>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"dashboard-cards\">\r\n");
      out.write("			    <div class=\"card\">\r\n");
      out.write("			        <h3>총 게시글 수</h3>\r\n");
      out.write("			        <div class=\"value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardTotalCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 개</div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			    <div class=\"card\" style=\"border-left-color: #2ecc71;\">\r\n");
      out.write("			        <h3>총 회원 수</h3>\r\n");
      out.write("			        <div class=\"value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalMemberCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 명</div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			    <div class=\"card\" style=\"border-left-color: #f1c40f;\">\r\n");
      out.write("			        <h3>신규 게시글 (오늘)</h3>\r\n");
      out.write("			        <div class=\"value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardTodayCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 건</div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"recent-members-section\">\r\n");
      out.write("			    <h3>최근 가입자 알림</h3>\r\n");
      out.write("			    <table class=\"admin-mini-table\">\r\n");
      out.write("			        <thead>\r\n");
      out.write("			            <tr>\r\n");
      out.write("			                <th width=\"30%\">아이디</th>\r\n");
      out.write("			                <th width=\"30%\">이름</th>\r\n");
      out.write("			                <th width=\"40%\">가입일</th>\r\n");
      out.write("			            </tr>\r\n");
      out.write("			        </thead>\r\n");
      out.write("			        <tbody>\r\n");
      out.write("			            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			        </tbody>\r\n");
      out.write("			    </table>\r\n");
      out.write("			</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/admin/main.jsp(119,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("m");
    // /WEB-INF/views/admin/main.jsp(119,15) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/main.jsp(119,15) '${recentMembers}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${recentMembers}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			                <tr>\r\n");
          out.write("			                    <td class=\"user-id\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("			                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("			                    <td class=\"reg-date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.regdateShort}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("			                </tr>\r\n");
          out.write("			            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/admin/main.jsp(126,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty recentMembers}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("			                <tr>\r\n");
        out.write("			                    <td colspan=\"3\" style=\"text-align:center; color:#ccc; padding:30px;\">최근 가입자가 없습니다.</td>\r\n");
        out.write("			                </tr>\r\n");
        out.write("			            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
