/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2026-01-07 09:53:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1767779110071L));
    _jspx_dependants.put("jar:file:/C:/Users/M/.m2/repository/org/springframework/security/spring-security-taglibs/6.4.2/spring-security-taglibs-6.4.2.jar!/META-INF/security.tld", Long.valueOf(1734333402000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1764828076780L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-6.4.2.jar", Long.valueOf(1767079630784L));
    _jspx_dependants.put("jar:file:/C:/Users/M/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시글 상세보기</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* 1. 기본 레이아웃 및 본문 스타일 */\r\n");
      out.write("    body { font-family: 'Malgun Gothic', sans-serif; background-color: #f4f7f6; margin: 0; }\r\n");
      out.write("    .container { width: 850px; margin: 40px auto; background: #fff; padding: 40px; border-radius: 12px; box-shadow: 0 5px 15px rgba(0,0,0,0.05); }\r\n");
      out.write("    \r\n");
      out.write("    .detail-header { border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }\r\n");
      out.write("    .detail-title { font-size: 28px; font-weight: bold; color: #222; margin-bottom: 15px; }\r\n");
      out.write("    \r\n");
      out.write("    .info-bar { display: flex; color: #888; font-size: 14px; gap: 20px; background: #f9f9f9; padding: 10px 15px; border-radius: 6px; }\r\n");
      out.write("    .info-bar b { color: #333; }\r\n");
      out.write("\r\n");
      out.write("    .content-area { \r\n");
      out.write("        margin-top: 30px; \r\n");
      out.write("        min-height: 400px; \r\n");
      out.write("        line-height: 1.8; \r\n");
      out.write("        font-size: 16px; \r\n");
      out.write("        color: #444; \r\n");
      out.write("        white-space: pre-wrap; \r\n");
      out.write("        border-bottom: 1px solid #eee;\r\n");
      out.write("        padding-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-area { display: flex; justify-content: space-between; margin-top: 30px; margin-bottom: 50px; }\r\n");
      out.write("    .btn { padding: 10px 25px; border-radius: 6px; cursor: pointer; font-size: 14px; font-weight: 600; text-decoration: none; border: none; transition: 0.2s; display: inline-block; }\r\n");
      out.write("    \r\n");
      out.write("    .btn-list { background-color: #6c757d; color: white; }\r\n");
      out.write("    .btn-modify { background-color: #007bff; color: white; }\r\n");
      out.write("    .btn-delete { background-color: #dc3545; color: white; }\r\n");
      out.write("    .btn:hover { opacity: 0.8; }\r\n");
      out.write("\r\n");
      out.write("    /* 2. 댓글 영역 스타일 */\r\n");
      out.write("    .reply-section-title { border-left: 5px solid #007bff; padding-left: 15px; margin-bottom: 25px; font-size: 20px; color: #333; }\r\n");
      out.write("    \r\n");
      out.write("    .reply-input-box { background: #f9f9f9; padding: 20px; border-radius: 8px; margin-bottom: 30px; border: 1px solid #eee; }\r\n");
      out.write("    #replyText { width: 100%; height: 80px; padding: 12px; border-radius: 6px; border: 1px solid #ddd; resize: none; box-sizing: border-box; font-family: inherit; }\r\n");
      out.write("\r\n");
      out.write("    #replyList { list-style: none; padding: 0; }\r\n");
      out.write("    .reply-item { background: #fff; border-bottom: 1px solid #eee; padding: 20px 10px; transition: 0.3s; }\r\n");
      out.write("    .reply-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }\r\n");
      out.write("    .replyer-name { font-weight: bold; color: #333; font-size: 15px; }\r\n");
      out.write("    .reply-content { color: #555; font-size: 15px; line-height: 1.6; }\r\n");
      out.write("    \r\n");
      out.write("    .reply-manage-btns a { font-size: 12px; color: #999; text-decoration: none; margin-left: 10px; }\r\n");
      out.write("    .reply-manage-btns a:hover { color: #007bff; text-decoration: underline; }\r\n");
      out.write("\r\n");
      out.write("    .edit-textarea { width: 100%; height: 70px; padding: 10px; border: 1px solid #007bff; border-radius: 6px; box-sizing: border-box; margin-bottom: 10px; }\r\n");
      out.write("\r\n");
      out.write("    /* 3. 페이징 버튼 스타일 */\r\n");
      out.write("    .paging-btn { display: inline-block; padding: 8px 14px; margin: 0 4px; border: 1px solid #ddd; border-radius: 4px; color: #666; text-decoration: none; font-size: 13px; font-weight: 500; transition: 0.2s; }\r\n");
      out.write("    .paging-btn:hover { background-color: #f4f4f4; border-color: #bbb; }\r\n");
      out.write("    .paging-btn.active { background-color: #007bff; color: white; border-color: #007bff; }\r\n");
      out.write("    .paging-arrow { background-color: #f9f9f9; font-weight: bold; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* CSS 스타일은 동일하므로 생략 (기존 스타일 그대로 유지하세요) */\r\n");
      out.write("    .top-navbar { background-color: #fff; border-bottom: 1px solid #dee2e6; padding: 0 40px; height: 50px; display: flex; justify-content: flex-end; align-items: center; box-shadow: 0 2px 4px rgba(0,0,0,0.03); margin-bottom: 25px; }\r\n");
      out.write("    .nav-menu { display: flex; align-items: center; gap: 15px; font-size: 13px; }\r\n");
      out.write("    .user-name { color: #888; margin-right: 5px; }\r\n");
      out.write("    .user-name b { color: #333; font-weight: 600; }\r\n");
      out.write("    .nav-link { color: #666; text-decoration: none; padding: 4px 8px; border-radius: 4px; transition: all 0.2s ease; }\r\n");
      out.write("    .nav-link:hover { background-color: #f1f3f5; color: #000; }\r\n");
      out.write("    .btn-logout { color: #aeafb0; }\r\n");
      out.write("    .btn-logout:hover { color: #dc3545; background-color: #fff5f5; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"top-navbar\">\r\n");
      out.write("    <div class=\"nav-menu\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"detail-header\">\r\n");
      out.write("        <div class=\"detail-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("        <div class=\"info-bar\">\r\n");
      out.write("            <span>번호: <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.seq}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></span>\r\n");
      out.write("            <span>작성자: <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></span>\r\n");
      out.write("            <span>작성일: <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.regdateShort}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></span>\r\n");
      out.write("            <span>조회수: <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.hit}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content-area\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"btn-area\">\r\n");
      out.write("	    <a href=\"/board/list?page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&size=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&types=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${types}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&keyword=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btn btn-list\">목록으로</a>\r\n");
      out.write("	    \r\n");
      out.write("	    <div class=\"btn-group\">\r\n");
      out.write("	        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"reply-wrapper\">\r\n");
      out.write("        <h3 class=\"reply-section-title\">댓글 <span id=\"replyCount\" style=\"color: #007bff;\">0</span></h3>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"reply-input-box\">\r\n");
      out.write("            <textarea id=\"replyText\" placeholder=\"댓글을 입력해주세요.\"></textarea>\r\n");
      out.write("            <div style=\"text-align: right; margin-top: 10px;\">\r\n");
      out.write("                <button id=\"addReplyBtn\" class=\"btn btn-modify\">댓글 등록</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <ul id=\"replyList\"></ul>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"replyPaging\" style=\"display: flex; justify-content: center; margin-top: 40px;\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const bno = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.seq}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; \r\n");
      out.write("    const loginId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; \r\n");
      out.write("    \r\n");
      out.write("    // 현재 페이지 번호를 기억하기 위한 변수 (값이 변하므로 let 사용)\r\n");
      out.write("    let currentPage = 1; \r\n");
      out.write("	\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("        printReplies(1); \r\n");
      out.write("\r\n");
      out.write("        // 댓글 등록 버튼 이벤트 연결\r\n");
      out.write("        document.getElementById(\"addReplyBtn\").addEventListener(\"click\", addReply);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 1. 댓글 목록 출력\r\n");
      out.write("    function printReplies(page) {\r\n");
      out.write("        // 호출된 페이지 번호를 현재 페이지로 저장\r\n");
      out.write("        currentPage = page; \r\n");
      out.write("        \r\n");
      out.write("        const url = \"/reply/list/\" + bno + \"?page=\" + page;\r\n");
      out.write("        fetch(url)\r\n");
      out.write("            .then(res => res.json())\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                document.getElementById(\"replyCount\").innerText = data.totalCount;\r\n");
      out.write("                let replyUL = document.getElementById(\"replyList\");\r\n");
      out.write("                let str = \"\";\r\n");
      out.write("                \r\n");
      out.write("                if(data.replyList && data.replyList.length > 0) {\r\n");
      out.write("                    data.replyList.forEach(reply => {\r\n");
      out.write("                        str += '<li class=\"reply-item\" id=\"reply-li-' + reply.rno + '\">';\r\n");
      out.write("                        str += '    <div class=\"reply-header\">';\r\n");
      out.write("                        str += '        <span class=\"replyer-name\">👤 ' + reply.replyer + '</span>';\r\n");
      out.write("                        \r\n");
      out.write("                        if(loginId === reply.replyer) {\r\n");
      out.write("                            str += '    <div class=\"reply-manage-btns\">';\r\n");
      out.write("                            str += '        <a href=\"javascript:showEditForm(' + reply.rno + ')\">수정</a>';\r\n");
      out.write("                            str += '        <a href=\"javascript:removeReply(' + reply.rno + ')\" style=\"color:#dc3545;\">삭제</a>';\r\n");
      out.write("                            str += '    </div>';\r\n");
      out.write("                        }\r\n");
      out.write("                        \r\n");
      out.write("                        str += '    </div>';\r\n");
      out.write("                        str += '    <div class=\"reply-content\">' + reply.replyText + '</div>';\r\n");
      out.write("                        str += '</li>';\r\n");
      out.write("                    });\r\n");
      out.write("                } else {\r\n");
      out.write("                    str = '<li style=\"text-align:center; padding: 40px 0; color: #999;\">등록된 댓글이 없습니다.</li>';\r\n");
      out.write("                }\r\n");
      out.write("                replyUL.innerHTML = str;\r\n");
      out.write("                printPaging(data);\r\n");
      out.write("            })\r\n");
      out.write("            .catch(err => console.error(\"댓글 로드 실패:\", err));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 2. 댓글 등록\r\n");
      out.write("    function addReply() {\r\n");
      out.write("        const replyText = document.getElementById(\"replyText\").value;\r\n");
      out.write("        if(!loginId) { alert(\"로그인이 필요합니다.\"); return; }\r\n");
      out.write("        if(!replyText) { alert(\"내용을 입력하세요.\"); return; }\r\n");
      out.write("\r\n");
      out.write("        fetch('/reply/add', {\r\n");
      out.write("            method: 'POST',\r\n");
      out.write("            headers: { 'Content-Type': 'application/json' },\r\n");
      out.write("            body: JSON.stringify({\r\n");
      out.write("                bno: bno,\r\n");
      out.write("                replyText: replyText,\r\n");
      out.write("                replyer: loginId\r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("        .then(res => res.text())\r\n");
      out.write("        .then(data => {\r\n");
      out.write("            if(data === \"success\") {\r\n");
      out.write("                alert(\"댓글이 등록되었습니다.\");\r\n");
      out.write("                document.getElementById(\"replyText\").value = \"\";\r\n");
      out.write("                // 새 댓글 등록 시에는 보통 1페이지로 가는 것이 일반적입니다.\r\n");
      out.write("                printReplies(1); \r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 3. 수정 폼 전환\r\n");
      out.write("    function showEditForm(rno) {\r\n");
      out.write("        const li = document.getElementById('reply-li-' + rno);\r\n");
      out.write("        const contentDiv = li.querySelector('.reply-content');\r\n");
      out.write("        const originalText = contentDiv.innerText;\r\n");
      out.write("\r\n");
      out.write("        let editHtml = '<textarea class=\"edit-textarea\">' + originalText + '</textarea>';\r\n");
      out.write("        editHtml += '<div style=\"text-align:right;\">';\r\n");
      out.write("        editHtml += '   <button onclick=\"modifyReply(' + rno + ')\" class=\"btn btn-modify\" style=\"padding:5px 15px; font-size:12px;\">완료</button>';\r\n");
      out.write("        // 취소 시 현재 보고 있던 페이지(currentPage)를 다시 호출하도록 수정\r\n");
      out.write("        editHtml += '   <button onclick=\"printReplies(currentPage)\" class=\"btn btn-list\" style=\"padding:5px 15px; font-size:12px; margin-left:5px;\">취소</button>';\r\n");
      out.write("        editHtml += '</div>';\r\n");
      out.write("\r\n");
      out.write("        contentDiv.innerHTML = editHtml;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 4. 서버에 수정 전송 (@RequestBody 방식)\r\n");
      out.write("    function modifyReply(rno) {\r\n");
      out.write("        const li = document.getElementById('reply-li-' + rno);\r\n");
      out.write("        const modText = li.querySelector('.edit-textarea').value;\r\n");
      out.write("\r\n");
      out.write("        if(!modText) { alert(\"내용을 입력하세요.\"); return; }\r\n");
      out.write("\r\n");
      out.write("        fetch('/reply/modify', {\r\n");
      out.write("            method: 'POST',\r\n");
      out.write("            headers: { 'Content-Type': 'application/json' },\r\n");
      out.write("            body: JSON.stringify({ rno: rno, replyText: modText })\r\n");
      out.write("        })\r\n");
      out.write("        .then(res => res.text())\r\n");
      out.write("        .then(data => {\r\n");
      out.write("            if(data === \"success\") {\r\n");
      out.write("                alert(\"댓글이 수정되었습니다.\");\r\n");
      out.write("                // 수정 완료 후 현재 페이지(currentPage) 유지\r\n");
      out.write("                printReplies(currentPage);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 5. 삭제 처리\r\n");
      out.write("    function removeReply(rno) {\r\n");
      out.write("        if(!confirm(\"정말 삭제하시겠습니까?\")) return;\r\n");
      out.write("        \r\n");
      out.write("        fetch('/reply/delete?rno=' + rno, { \r\n");
      out.write("            method: 'POST' \r\n");
      out.write("        })\r\n");
      out.write("        .then(res => res.text())\r\n");
      out.write("        .then(data => {\r\n");
      out.write("            if(data.trim() === \"success\") {\r\n");
      out.write("                alert(\"댓글이 삭제되었습니다.\");\r\n");
      out.write("                // 삭제 후 현재 페이지 유지 (데이터가 다 삭제되어 비어있을 경우를 대비해 로직 보강 가능)\r\n");
      out.write("                printReplies(currentPage);\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"삭제 실패\");\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        .catch(err => console.error(\"삭제 실패:\", err));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 6. 페이징 출력\r\n");
      out.write("    function printPaging(data) {\r\n");
      out.write("        let pagingDiv = document.getElementById(\"replyPaging\");\r\n");
      out.write("        let str = \"\";\r\n");
      out.write("        if(data.prev) {\r\n");
      out.write("            str += \"<a href='javascript:printReplies(\" + (data.start - 1) + \")' class='paging-btn paging-arrow'>&lt;</a>\";\r\n");
      out.write("        }\r\n");
      out.write("        data.pageNums.forEach(num => {\r\n");
      out.write("            // data.page가 현재 서버에서 온 페이지 번호이므로 이를 이용해 active 표시\r\n");
      out.write("            let activeClass = (num === data.page) ? \"active\" : \"\";\r\n");
      out.write("            str += \"<a href='javascript:printReplies(\" + num + \")' class='paging-btn \" + activeClass + \"'>\" + num + \"</a>\";\r\n");
      out.write("        });\r\n");
      out.write("        if(data.next) {\r\n");
      out.write("            str += \"<a href='javascript:printReplies(\" + (data.end + 1) + \")' class='paging-btn paging-arrow'>&gt;</a>\";\r\n");
      out.write("        }\r\n");
      out.write("        pagingDiv.innerHTML = str;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sec_005fauthorize_005f0.setParent(null);
    // /WEB-INF/views/common/header.jsp(21,8) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous()");
    int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
    if (_jspx_eval_sec_005fauthorize_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/\" class=\"nav-link\">로그인</a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/join\" class=\"nav-link\">회원가입</a>\r\n");
      out.write("        ");
    }
    if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
    _jspx_th_sec_005fauthorize_005f1.setParent(null);
    // /WEB-INF/views/common/header.jsp(27,8) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
    int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
    if (_jspx_eval_sec_005fauthorize_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write("\r\n");
      out.write("            <div class=\"user-name\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <b>");
      if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
        return true;
      out.write("</b>님\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/update\" class=\"nav-link\">내 정보 수정</a>\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/logout\" class=\"nav-link btn-logout\">로그아웃</a>\r\n");
      out.write("        ");
    }
    if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sec_005fauthentication_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
    // /WEB-INF/views/common/header.jsp(30,19) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sec_005fauthentication_005f0.setProperty("principal.username");
    int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
    if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/board/detail.jsp(83,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.id == board.writer}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("	            <a href=\"/board/modify?seq=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.seq}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&page=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&types=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${types}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&keyword=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" class=\"btn btn-modify\">수정하기</a>\r\n");
        out.write("	            \r\n");
        out.write("	            <a href=\"/board/delete?seq=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.seq}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&page=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&types=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${types}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&keyword=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" \r\n");
        out.write("	               class=\"btn btn-delete\" \r\n");
        out.write("	               onclick=\"return confirm('게시글을 정말 삭제하시겠습니까?');\">삭제</a>\r\n");
        out.write("	        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
