/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-31 08:42:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>회원가입</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: 'Arial', sans-serif; background-color: #f4f7f6; margin: 0; padding: 50px 0; display: flex; justify-content: center; }\r\n");
      out.write("        .join-container { background: white; padding: 40px; border-radius: 10px; box-shadow: 0 10px 25px rgba(0,0,0,0.1); width: 450px; }\r\n");
      out.write("        h2 { text-align: center; color: #333; margin-bottom: 30px; }\r\n");
      out.write("        .form-group { margin-bottom: 15px; }\r\n");
      out.write("        label { display: block; margin-bottom: 5px; font-weight: bold; color: #555; }\r\n");
      out.write("        input, select { width: 100%; padding: 10px; border: 1px solid #ddd; border-radius: 5px; box-sizing: border-box; }\r\n");
      out.write("        \r\n");
      out.write("        /* 관리자 코드 입력창 - 처음엔 숨김 */\r\n");
      out.write("        #adminCodeGroup { display: none; background-color: #fff9e6; padding: 10px; border-radius: 5px; border: 1px dashed #ffcc00; margin-top: 10px; }\r\n");
      out.write("        \r\n");
      out.write("        .btn-submit { width: 100%; padding: 12px; background-color: #4e73df; color: white; border: none; border-radius: 5px; font-size: 16px; font-weight: bold; cursor: pointer; margin-top: 20px; }\r\n");
      out.write("        .btn-submit:hover { background-color: #2e59d9; }\r\n");
      out.write("        .link-login { display: block; text-align: center; margin-top: 15px; color: #888; text-decoration: none; font-size: 14px; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"join-container\">\r\n");
      out.write("        <h2>회원가입</h2>\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/join\" method=\"post\" onsubmit=\"return validateForm()\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>아이디</label>\r\n");
      out.write("                <input type=\"text\" name=\"id\" required placeholder=\"아이디를 입력하세요\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>비밀번호</label>\r\n");
      out.write("                <input type=\"password\" name=\"password\" required placeholder=\"비밀번호를 입력하세요\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>이름</label>\r\n");
      out.write("                <input type=\"text\" name=\"name\" required placeholder=\"이름을 입력하세요\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>이메일</label>\r\n");
      out.write("                <input type=\"email\" name=\"email\" required placeholder=\"example@mail.com\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>전화번호</label>\r\n");
      out.write("                <input type=\"tel\" name=\"phone\" required placeholder=\"010-0000-0000\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>회원 등급</label>\r\n");
      out.write("                <select name=\"role\" id=\"roleSelect\" onchange=\"toggleAdminField()\">\r\n");
      out.write("                    <option value=\"USER\">일반회원</option>\r\n");
      out.write("                    <option value=\"ADMIN\">관리자</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"adminCodeGroup\" class=\"form-group\">\r\n");
      out.write("                <label style=\"color: #d9534f;\">관리자 인증 코드</label>\r\n");
      out.write("                <input type=\"password\" id=\"adminCode\" name=\"adminCode\" placeholder=\"관리자 보안 코드를 입력하세요\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"btn-submit\">가입하기</button>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"link-login\">이미 계정이 있나요? 로그인 페이지로</a>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // 1. 관리자 선택 여부에 따라 입력창 보여주기/숨기기\r\n");
      out.write("        function toggleAdminField() {\r\n");
      out.write("            const role = document.getElementById('roleSelect').value;\r\n");
      out.write("            const adminGroup = document.getElementById('adminCodeGroup');\r\n");
      out.write("            \r\n");
      out.write("            if (role === 'ADMIN') {\r\n");
      out.write("                adminGroup.style.display = 'block';\r\n");
      out.write("            } else {\r\n");
      out.write("                adminGroup.style.display = 'none';\r\n");
      out.write("                document.getElementById('adminCode').value = ''; // 입력값 초기화\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 2. 가입 전 간단한 유효성 검사\r\n");
      out.write("        function validateForm() {\r\n");
      out.write("            const role = document.getElementById('roleSelect').value;\r\n");
      out.write("            const adminCode = document.getElementById('adminCode').value;\r\n");
      out.write("\r\n");
      out.write("            if (role === 'ADMIN' && adminCode === '') {\r\n");
      out.write("                alert('관리자 가입을 위해서는 인증 코드가 필수입니다.');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
