/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2026-01-07 08:11:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.member;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class memberList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1764828076780L));
    _jspx_dependants.put("jar:file:/C:/Users/M/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>관리자 - 회원 관리</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body { margin: 0; font-family: 'Malgun Gothic', sans-serif; display: flex; background-color: #f4f7f6; }\r\n");
      out.write("    \r\n");
      out.write("    /* 사이드바 스타일 */\r\n");
      out.write("    .sidebar { width: 240px; background: #2c3e50; color: white; height: 100vh; position: fixed; }\r\n");
      out.write("    .sidebar-header { padding: 20px; text-align: center; background: #1a252f; font-size: 20px; font-weight: bold; }\r\n");
      out.write("    .sidebar-menu { padding: 0; list-style: none; }\r\n");
      out.write("    .sidebar-menu li a { display: block; padding: 15px 25px; color: #bdc3c7; text-decoration: none; border-bottom: 1px solid #34495e; }\r\n");
      out.write("    .sidebar-menu li a:hover { background: #34495e; color: white; }\r\n");
      out.write("    .sidebar-menu li a.active { background: #3498db; color: white; }\r\n");
      out.write("\r\n");
      out.write("    /* 메인 영역 */\r\n");
      out.write("    .main-content { margin-left: 240px; width: calc(100% - 240px); }\r\n");
      out.write("    .container { padding: 30px; }\r\n");
      out.write("    .page-title { margin-bottom: 10px; color: #333; }\r\n");
      out.write("\r\n");
      out.write("    /* 검색 영역 (통일된 search-wrapper) */\r\n");
      out.write("    .search-wrapper { margin-bottom: 20px; display: flex; justify-content: flex-end; gap: 8px; }\r\n");
      out.write("    .search-wrapper select, .search-wrapper input { padding: 8px; border: 1px solid #ddd; border-radius: 4px; outline: none; }\r\n");
      out.write("    .search-wrapper button { padding: 8px 18px; background: #2c3e50; color: white; border: none; border-radius: 4px; cursor: pointer; }\r\n");
      out.write("    .search-wrapper button:hover { background: #1a252f; }\r\n");
      out.write("\r\n");
      out.write("    /* 테이블 스타일 */\r\n");
      out.write("    .admin-table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }\r\n");
      out.write("    .admin-table th { background: #f8f9fa; padding: 15px; border-bottom: 2px solid #dee2e6; color: #495057; font-size: 14px; }\r\n");
      out.write("    .admin-table td { padding: 15px; border-bottom: 1px solid #eee; text-align: center; font-size: 14px; color: #666; }\r\n");
      out.write("\r\n");
      out.write("    /* 배지 및 상태 스타일 */\r\n");
      out.write("    .badge { padding: 4px 8px; border-radius: 12px; font-size: 11px; font-weight: bold; }\r\n");
      out.write("    .badge-admin { background: #e8f4fd; color: #3498db; }\r\n");
      out.write("    .badge-user { background: #f1f3f5; color: #868e96; }\r\n");
      out.write("    .badge-active { background: #e6fffa; color: #38b2ac; }\r\n");
      out.write("    .badge-disabled { background: #fff5f5; color: #e74c3c; }\r\n");
      out.write("    \r\n");
      out.write("    .disabled-row { background-color: #fcfcfc; }\r\n");
      out.write("    .disabled-row td { color: #ccc !important; }\r\n");
      out.write("\r\n");
      out.write("    /* 버튼 스타일 */\r\n");
      out.write("    .btn-action { border: none; padding: 8px 12px; border-radius: 4px; cursor: pointer; font-size: 12px; min-width: 70px; }\r\n");
      out.write("    .btn-kick { background: #e74c3c; color: white; }\r\n");
      out.write("    .btn-restore { background: #3498db; color: white; }\r\n");
      out.write("\r\n");
      out.write("    /* 페이징 */\r\n");
      out.write("    .pagination { display: flex; justify-content: center; list-style: none; padding: 0; margin-top: 30px; gap: 5px; }\r\n");
      out.write("    .pagination li a { display: block; padding: 8px 14px; border: 1px solid #ddd; text-decoration: none; color: #333; border-radius: 4px; background: white; }\r\n");
      out.write("    .pagination li.active a { background: #3498db; color: white; border-color: #3498db; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-header\">회원 관리</div>\r\n");
      out.write("        <ul class=\"sidebar-menu\">\r\n");
      out.write("            <li><a href=\"/admin/main\">대시보드 메인</a></li>\r\n");
      out.write("            <li><a href=\"/admin/board/list\">게시판 관리</a></li>\r\n");
      out.write("            <li><a href=\"/admin/member/list\" class=\"active\">회원 관리</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/adminHeader.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h1 class=\"page-title\">회원 관리</h1>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"search-wrapper\">\r\n");
      out.write("                <select id=\"searchType\">\r\n");
      out.write("                    <option value=\"i\">아이디</option>\r\n");
      out.write("                    <option value=\"n\">이름</option>\r\n");
      out.write("                    <option value=\"e\">이메일</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <input type=\"text\" id=\"searchKeyword\" placeholder=\"검색어 입력\">\r\n");
      out.write("                <button type=\"button\" onclick=\"loadMemberList(1)\">검색</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <table class=\"admin-table\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th width=\"100\">상태</th>\r\n");
      out.write("                        <th width=\"150\">아이디</th>\r\n");
      out.write("                        <th width=\"120\">이름</th>\r\n");
      out.write("                        <th>이메일</th>\r\n");
      out.write("                        <th width=\"100\">권한</th>\r\n");
      out.write("                        <th width=\"120\">가입일</th>\r\n");
      out.write("                        <th width=\"120\">관리</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody id=\"memberListBody\">\r\n");
      out.write("                    <tr><td colspan=\"7\">로딩 중...</td></tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"pagination\" id=\"memberPaging\"></ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const loginId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    let currentPage = 1;\r\n");
      out.write("\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("        loadMemberList(1);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function loadMemberList(page) {\r\n");
      out.write("        currentPage = page;\r\n");
      out.write("        const type = document.getElementById(\"searchType\").value;\r\n");
      out.write("        const keyword = document.getElementById(\"searchKeyword\").value;\r\n");
      out.write("        \r\n");
      out.write("        const url = \"/admin/member/api/list?page=\" + page + \"&size=10&types=\" + type + \"&keyword=\" + encodeURIComponent(keyword);\r\n");
      out.write("\r\n");
      out.write("        fetch(url)\r\n");
      out.write("            .then(res => res.json())\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                printTable(data.memberDTOList); \r\n");
      out.write("                printPaging(data);\r\n");
      out.write("            })\r\n");
      out.write("            .catch(err => {\r\n");
      out.write("                console.error(\"실패:\", err);\r\n");
      out.write("                document.getElementById(\"memberListBody\").innerHTML = '<tr><td colspan=\"7\" style=\"padding:50px; color:red;\">데이터 로드 실패</td></tr>';\r\n");
      out.write("            });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function printTable(list) {\r\n");
      out.write("        var tbody = document.getElementById(\"memberListBody\");\r\n");
      out.write("        var str = \"\";\r\n");
      out.write("        \r\n");
      out.write("        if(!list || list.length === 0) {\r\n");
      out.write("            tbody.innerHTML = '<tr><td colspan=\"7\" style=\"padding:50px;\">데이터가 없습니다.</td></tr>';\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        list.forEach(function(m) {\r\n");
      out.write("            var mid = m.id || \"-\";\r\n");
      out.write("            var mname = m.name || \"-\";\r\n");
      out.write("            var memail = m.email || \"-\";\r\n");
      out.write("            var mrole = m.role || \"MEMBER\";\r\n");
      out.write("            var enabled = m.enabled;\r\n");
      out.write("            var regDate = m.regdateShort || \"-\";\r\n");
      out.write("\r\n");
      out.write("            var disabledClass = enabled ? \"\" : \"disabled-row\";\r\n");
      out.write("            var statusBadge = enabled ? \"badge-active\" : \"badge-disabled\";\r\n");
      out.write("            var statusText = enabled ? \"활동중\" : \"탈퇴됨\";\r\n");
      out.write("            var roleBadge = mrole === 'ADMIN' ? \"badge-admin\" : \"badge-user\";\r\n");
      out.write("\r\n");
      out.write("            str += '<tr class=\"' + disabledClass + '\">';\r\n");
      out.write("            str += '    <td><span class=\"badge ' + statusBadge + '\">' + statusText + '</span></td>';\r\n");
      out.write("            str += '    <td><b>' + mid + '</b></td>';\r\n");
      out.write("            str += '    <td>' + mname + '</td>';\r\n");
      out.write("            str += '    <td>' + memail + '</td>';\r\n");
      out.write("            str += '    <td><span class=\"badge ' + roleBadge + '\">' + mrole + '</span></td>';\r\n");
      out.write("            str += '    <td>' + regDate + '</td>';\r\n");
      out.write("            str += '    <td>';\r\n");
      out.write("            \r\n");
      out.write("            if(mid !== loginId) {\r\n");
      out.write("                if(enabled) {\r\n");
      out.write("                    str += '<button type=\"button\" class=\"btn-action btn-kick\" onclick=\"changeStatus(\\'' + mid + '\\', false)\">탈퇴</button>';\r\n");
      out.write("                } else {\r\n");
      out.write("                    str += '<button type=\"button\" class=\"btn-action btn-restore\" onclick=\"changeStatus(\\'' + mid + '\\', true)\">복구</button>';\r\n");
      out.write("                }\r\n");
      out.write("            } else {\r\n");
      out.write("                str += '<span class=\"badge badge-admin\">나(관리자)</span>';\r\n");
      out.write("            }\r\n");
      out.write("            str += '    </td>';\r\n");
      out.write("            str += '</tr>';\r\n");
      out.write("        });\r\n");
      out.write("        tbody.innerHTML = str;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function printPaging(data) {\r\n");
      out.write("        var pagingUl = document.getElementById(\"memberPaging\");\r\n");
      out.write("        var str = \"\";\r\n");
      out.write("        \r\n");
      out.write("        if(data.prev) {\r\n");
      out.write("            str += '<li><a href=\"javascript:loadMemberList(' + (data.start - 1) + ')\">이전</a></li>';\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(data.pageNums && data.pageNums.length > 0) {\r\n");
      out.write("            data.pageNums.forEach(function(num) {\r\n");
      out.write("                var activeClass = (data.page === num) ? \"active\" : \"\";\r\n");
      out.write("                str += '<li class=\"' + activeClass + '\"><a href=\"javascript:loadMemberList(' + num + ')\">' + num + '</a></li>';\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(data.next) {\r\n");
      out.write("            str += '<li><a href=\"javascript:loadMemberList(' + (data.end + 1) + ')\">다음</a></li>';\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        pagingUl.innerHTML = str;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function changeStatus(id, enabled) {\r\n");
      out.write("        const actionText = enabled ? \"복구\" : \"탈퇴\";\r\n");
      out.write("        if(!confirm(id + \" 회원을 \" + actionText + \" 처리하시겠습니까?\")) return;\r\n");
      out.write("        \r\n");
      out.write("        fetch(\"/admin/updateEnabled\", {\r\n");
      out.write("            method: 'POST',\r\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\r\n");
      out.write("            body: \"id=\" + id + \"&enabled=\" + enabled\r\n");
      out.write("        })\r\n");
      out.write("        .then(res => res.text())\r\n");
      out.write("        .then(msg => {\r\n");
      out.write("            alert(msg);\r\n");
      out.write("            loadMemberList(currentPage);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
